### ISSUE TITLE
Errors:Filter must be an array.

### ISSUE THREAD

**Issue by alsosweet** [KodepandaID/go-onesignal-sdk#1]
type NotificationOpt struct {
	AppID   string        `json:"app_id,omitempty"`
	Filters []interface{} `json:"filters,omitempty"` **//Here I am modified to an array, test OK.**
	SpecificDevice
	NotificationContent
	EmailContent
	Attachments
	ActionButtons
	Appearance
	Delivery
	Grouping
	Platform
}

**Comment by LordAur** [comment]
I change it, here [1e20ab7](https://github.com/KodepandaID/go-onesignal-sdk/commit/1e20ab74ac97dc8906c41dda00ea113f323becdf)

Thanks 👍
